image: jangrewe/gitlab-ci-android

variables:
  ANDROID_COMPILE_SDK: "28"
  APP_NAME: $CI_PROJECT_NAME

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .m2/
    - .gradle/

stages:
  - build
  - package

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  - chmod +x ./make_dictionaries.sh
  - apt-get update -y && apt-get install wget openssl -y
  - ./make_dictionaries.sh


########################################################################
# BUILD

.build_template: &build
  stage: build
  artifacts:
    expire_in: 4 hours
    paths:
      - app/build/outputs/

build:develop:
  <<: *build
  except:
    - production

  script:
    - ./gradlew assembleDebug

build:release:
  <<: *build
  only:
    - production
  script:
    - ./gradlew assembleRelease


########################################################################
# PACKAGE

.package_template: &package
  before_script:
    - export VERSION_NAME=`egrep '^[[:blank:]]+versionName[[:blank:]]'  app/build.gradle | awk '{print $2}' | sed s/\"//g`
    - mkdir -p exported

package:develop:
  <<: *package
  stage: package
  environment: Development
  except:
    - production
  script:
    - mv app/build/outputs/apk/debug/app-debug.apk ./exported/${APP_NAME}-v$VERSION_NAME-debug.apk
  dependencies:
    - build:develop
  artifacts:
    expire_in: 7 days
    paths:
      - exported

package:release:unsigned:
  <<: *package
  stage: package
  environment: Release
  only:
    - production
  script:
    - mv app/build/outputs/apk/release/app-release-unsigned.apk ./exported/release-unsigned.apk
  dependencies:
    - build:release
  artifacts:
    expire_in: 1 month
    paths:
      - exported

